swagger: "2.0"
info:
  version: "0.0.1"
  title: fakeOrbit

host: localhost:3001

basePath: /

schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: users
    get:
      operationId: getAllUsers
      description: ''
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsers"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /blog:
    x-swagger-router-controller: blog
    get:
      operationId: getAllPost
      description: ''
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetBlog"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:

  GetUsers:
    properties:
      users:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            lastname1:
              type: string
            lastname2:
              type: string
            birthdate:
              type: string
            picture:
              type: string
  GetBlog:
    properties:
      blog:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            id_user:
              type: string
            title:
              type: string
            description:
              type: string
            text:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string